/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 89
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 50
#define ALIAS_COUNT 0
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 14
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 15
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_namespace = 1,
  anon_sym_EQ = 2,
  aux_sym__header_section_namespaced_token1 = 3,
  anon_sym_condition = 4,
  aux_sym_present_section_token1 = 5,
  anon_sym_LBRACK = 6,
  anon_sym_ShaderOverride = 7,
  anon_sym_RBRACK = 8,
  anon_sym_hash = 9,
  anon_sym_allow_duplicate_hash = 10,
  anon_sym_overrule = 11,
  anon_sym_true = 12,
  anon_sym_false = 13,
  anon_sym_DOLLAR = 14,
  anon_sym_post = 15,
  anon_sym_pre = 16,
  anon_sym_local = 17,
  anon_sym_global = 18,
  aux_sym_commandlist_rarg_token1 = 19,
  anon_sym_SEMI = 20,
  sym_hash_16 = 21,
  aux_sym_float_token1 = 22,
  aux_sym_float_token2 = 23,
  sym_source_file = 24,
  sym_header_section = 25,
  sym__header_section_namespaced = 26,
  sym__header_section_conditioned = 27,
  sym__section = 28,
  sym__named_section = 29,
  sym__regular_section = 30,
  sym_present_section = 31,
  sym_shader_override = 32,
  sym_allow_duplicate_hash_value = 33,
  sym__expression = 34,
  sym_assignment = 35,
  sym_variable = 36,
  sym__key = 37,
  sym__value = 38,
  sym_eval_value = 39,
  sym_timing_prefix = 40,
  sym_scope_prefix = 41,
  sym_commandlist = 42,
  sym_commandlist_rarg = 43,
  sym_identifier = 44,
  sym_comment = 45,
  sym_string = 46,
  sym_float = 47,
  aux_sym_source_file_repeat1 = 48,
  aux_sym_present_section_repeat1 = 49,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_namespace] = "namespace",
  [anon_sym_EQ] = "=",
  [aux_sym__header_section_namespaced_token1] = "_header_section_namespaced_token1",
  [anon_sym_condition] = "condition",
  [aux_sym_present_section_token1] = "present_section_token1",
  [anon_sym_LBRACK] = "[",
  [anon_sym_ShaderOverride] = "ShaderOverride",
  [anon_sym_RBRACK] = "]",
  [anon_sym_hash] = "hash",
  [anon_sym_allow_duplicate_hash] = "allow_duplicate_hash",
  [anon_sym_overrule] = "overrule",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_post] = "post",
  [anon_sym_pre] = "pre",
  [anon_sym_local] = "local",
  [anon_sym_global] = "global",
  [aux_sym_commandlist_rarg_token1] = "commandlist_rarg_token1",
  [anon_sym_SEMI] = ";",
  [sym_hash_16] = "hash_16",
  [aux_sym_float_token1] = "float_token1",
  [aux_sym_float_token2] = "float_token2",
  [sym_source_file] = "source_file",
  [sym_header_section] = "header_section",
  [sym__header_section_namespaced] = "_header_section_namespaced",
  [sym__header_section_conditioned] = "_header_section_conditioned",
  [sym__section] = "_section",
  [sym__named_section] = "_named_section",
  [sym__regular_section] = "_regular_section",
  [sym_present_section] = "present_section",
  [sym_shader_override] = "shader_override",
  [sym_allow_duplicate_hash_value] = "allow_duplicate_hash_value",
  [sym__expression] = "_expression",
  [sym_assignment] = "assignment",
  [sym_variable] = "variable",
  [sym__key] = "_key",
  [sym__value] = "_value",
  [sym_eval_value] = "eval_value",
  [sym_timing_prefix] = "timing_prefix",
  [sym_scope_prefix] = "scope_prefix",
  [sym_commandlist] = "commandlist",
  [sym_commandlist_rarg] = "commandlist_rarg",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [sym_string] = "string",
  [sym_float] = "float",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_present_section_repeat1] = "present_section_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_namespace] = anon_sym_namespace,
  [anon_sym_EQ] = anon_sym_EQ,
  [aux_sym__header_section_namespaced_token1] = aux_sym__header_section_namespaced_token1,
  [anon_sym_condition] = anon_sym_condition,
  [aux_sym_present_section_token1] = aux_sym_present_section_token1,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_ShaderOverride] = anon_sym_ShaderOverride,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_hash] = anon_sym_hash,
  [anon_sym_allow_duplicate_hash] = anon_sym_allow_duplicate_hash,
  [anon_sym_overrule] = anon_sym_overrule,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_post] = anon_sym_post,
  [anon_sym_pre] = anon_sym_pre,
  [anon_sym_local] = anon_sym_local,
  [anon_sym_global] = anon_sym_global,
  [aux_sym_commandlist_rarg_token1] = aux_sym_commandlist_rarg_token1,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_hash_16] = sym_hash_16,
  [aux_sym_float_token1] = aux_sym_float_token1,
  [aux_sym_float_token2] = aux_sym_float_token2,
  [sym_source_file] = sym_source_file,
  [sym_header_section] = sym_header_section,
  [sym__header_section_namespaced] = sym__header_section_namespaced,
  [sym__header_section_conditioned] = sym__header_section_conditioned,
  [sym__section] = sym__section,
  [sym__named_section] = sym__named_section,
  [sym__regular_section] = sym__regular_section,
  [sym_present_section] = sym_present_section,
  [sym_shader_override] = sym_shader_override,
  [sym_allow_duplicate_hash_value] = sym_allow_duplicate_hash_value,
  [sym__expression] = sym__expression,
  [sym_assignment] = sym_assignment,
  [sym_variable] = sym_variable,
  [sym__key] = sym__key,
  [sym__value] = sym__value,
  [sym_eval_value] = sym_eval_value,
  [sym_timing_prefix] = sym_timing_prefix,
  [sym_scope_prefix] = sym_scope_prefix,
  [sym_commandlist] = sym_commandlist,
  [sym_commandlist_rarg] = sym_commandlist_rarg,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [sym_string] = sym_string,
  [sym_float] = sym_float,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_present_section_repeat1] = aux_sym_present_section_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_namespace] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__header_section_namespaced_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_condition] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_present_section_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ShaderOverride] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_hash] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_allow_duplicate_hash] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_overrule] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_post] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pre] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_local] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_global] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_commandlist_rarg_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_hash_16] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_float_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_float_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_header_section] = {
    .visible = true,
    .named = true,
  },
  [sym__header_section_namespaced] = {
    .visible = false,
    .named = true,
  },
  [sym__header_section_conditioned] = {
    .visible = false,
    .named = true,
  },
  [sym__section] = {
    .visible = false,
    .named = true,
  },
  [sym__named_section] = {
    .visible = false,
    .named = true,
  },
  [sym__regular_section] = {
    .visible = false,
    .named = true,
  },
  [sym_present_section] = {
    .visible = true,
    .named = true,
  },
  [sym_shader_override] = {
    .visible = true,
    .named = true,
  },
  [sym_allow_duplicate_hash_value] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym__key] = {
    .visible = false,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_eval_value] = {
    .visible = true,
    .named = true,
  },
  [sym_timing_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_scope_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_commandlist] = {
    .visible = true,
    .named = true,
  },
  [sym_commandlist_rarg] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_present_section_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_allow_duplicate_hash = 1,
  field_body = 2,
  field_condition = 3,
  field_hash = 4,
  field_name = 5,
  field_namespace = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_allow_duplicate_hash] = "allow_duplicate_hash",
  [field_body] = "body",
  [field_condition] = "condition",
  [field_hash] = "hash",
  [field_name] = "name",
  [field_namespace] = "namespace",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 2},
  [7] = {.index = 8, .length = 2},
  [8] = {.index = 10, .length = 2},
  [9] = {.index = 12, .length = 2},
  [10] = {.index = 14, .length = 2},
  [11] = {.index = 16, .length = 3},
  [12] = {.index = 19, .length = 3},
  [13] = {.index = 22, .length = 3},
  [14] = {.index = 25, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_condition, 0, .inherited = true},
    {field_namespace, 0, .inherited = true},
  [2] =
    {field_name, 1},
  [3] =
    {field_namespace, 2},
  [4] =
    {field_condition, 2},
  [5] =
    {field_name, 2},
  [6] =
    {field_body, 5},
    {field_name, 2},
  [8] =
    {field_condition, 6},
    {field_namespace, 2},
  [10] =
    {field_condition, 2},
    {field_namespace, 6},
  [12] =
    {field_hash, 7},
    {field_name, 2},
  [14] =
    {field_allow_duplicate_hash, 7},
    {field_name, 2},
  [16] =
    {field_body, 9},
    {field_hash, 7},
    {field_name, 2},
  [19] =
    {field_allow_duplicate_hash, 7},
    {field_body, 9},
    {field_name, 2},
  [22] =
    {field_allow_duplicate_hash, 11},
    {field_hash, 7},
    {field_name, 2},
  [25] =
    {field_allow_duplicate_hash, 11},
    {field_body, 13},
    {field_hash, 7},
    {field_name, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 24,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 25,
  [88] = 88,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(119);
      ADVANCE_MAP(
        '\n', 122,
        '\r', 1,
        '$', 134,
        '0', 7,
        ';', 165,
        '=', 121,
        'S', 47,
        '[', 125,
        ']', 127,
        'a', 60,
        'c', 70,
        'f', 17,
        'g', 55,
        'h', 13,
        'i', 62,
        'l', 67,
        'n', 14,
        'o', 95,
        'p', 71,
        't', 75,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(8);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(6);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(122);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(122);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ';') ADVANCE(165);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(164);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(122);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ';') ADVANCE(165);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(124);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(124);
      if (lookahead == '\r') ADVANCE(4);
      END_STATE();
    case 6:
      if (lookahead == '.') ADVANCE(100);
      if (lookahead == '_') ADVANCE(99);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(98);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '.') ADVANCE(100);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(98);
      END_STATE();
    case 8:
      if (lookahead == '0') ADVANCE(7);
      if (lookahead == 'i') ADVANCE(62);
      if (lookahead == 'n') ADVANCE(18);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(6);
      END_STATE();
    case 9:
      if (lookahead == 'O') ADVANCE(96);
      END_STATE();
    case 10:
      if (lookahead == ']') ADVANCE(5);
      END_STATE();
    case 11:
      if (lookahead == '_') ADVANCE(28);
      END_STATE();
    case 12:
      if (lookahead == '_') ADVANCE(48);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(84);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(61);
      END_STATE();
    case 15:
      if (lookahead == 'a') ADVANCE(30);
      END_STATE();
    case 16:
      if (lookahead == 'a') ADVANCE(25);
      END_STATE();
    case 17:
      if (lookahead == 'a') ADVANCE(56);
      END_STATE();
    case 18:
      if (lookahead == 'a') ADVANCE(63);
      END_STATE();
    case 19:
      if (lookahead == 'a') ADVANCE(53);
      END_STATE();
    case 20:
      if (lookahead == 'a') ADVANCE(91);
      END_STATE();
    case 21:
      if (lookahead == 'a') ADVANCE(54);
      END_STATE();
    case 22:
      if (lookahead == 'a') ADVANCE(85);
      END_STATE();
    case 23:
      if (lookahead == 'b') ADVANCE(21);
      END_STATE();
    case 24:
      if (lookahead == 'c') ADVANCE(20);
      END_STATE();
    case 25:
      if (lookahead == 'c') ADVANCE(35);
      END_STATE();
    case 26:
      if (lookahead == 'c') ADVANCE(19);
      END_STATE();
    case 27:
      if (lookahead == 'd') ADVANCE(49);
      END_STATE();
    case 28:
      if (lookahead == 'd') ADVANCE(92);
      END_STATE();
    case 29:
      if (lookahead == 'd') ADVANCE(36);
      END_STATE();
    case 30:
      if (lookahead == 'd') ADVANCE(40);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(137);
      END_STATE();
    case 32:
      if (lookahead == 'e') ADVANCE(132);
      END_STATE();
    case 33:
      if (lookahead == 'e') ADVANCE(133);
      END_STATE();
    case 34:
      if (lookahead == 'e') ADVANCE(131);
      END_STATE();
    case 35:
      if (lookahead == 'e') ADVANCE(120);
      END_STATE();
    case 36:
      if (lookahead == 'e') ADVANCE(126);
      END_STATE();
    case 37:
      if (lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 38:
      if (lookahead == 'e') ADVANCE(81);
      END_STATE();
    case 39:
      if (lookahead == 'e') ADVANCE(66);
      END_STATE();
    case 40:
      if (lookahead == 'e') ADVANCE(76);
      END_STATE();
    case 41:
      if (lookahead == 'e') ADVANCE(83);
      END_STATE();
    case 42:
      if (lookahead == 'e') ADVANCE(80);
      END_STATE();
    case 43:
      if (lookahead == 'e') ADVANCE(87);
      END_STATE();
    case 44:
      if (lookahead == 'f') ADVANCE(169);
      END_STATE();
    case 45:
      if (lookahead == 'h') ADVANCE(128);
      END_STATE();
    case 46:
      if (lookahead == 'h') ADVANCE(130);
      END_STATE();
    case 47:
      if (lookahead == 'h') ADVANCE(15);
      END_STATE();
    case 48:
      if (lookahead == 'h') ADVANCE(22);
      END_STATE();
    case 49:
      if (lookahead == 'i') ADVANCE(90);
      END_STATE();
    case 50:
      if (lookahead == 'i') ADVANCE(24);
      END_STATE();
    case 51:
      if (lookahead == 'i') ADVANCE(29);
      END_STATE();
    case 52:
      if (lookahead == 'i') ADVANCE(72);
      END_STATE();
    case 53:
      if (lookahead == 'l') ADVANCE(139);
      END_STATE();
    case 54:
      if (lookahead == 'l') ADVANCE(141);
      END_STATE();
    case 55:
      if (lookahead == 'l') ADVANCE(68);
      END_STATE();
    case 56:
      if (lookahead == 'l') ADVANCE(86);
      END_STATE();
    case 57:
      if (lookahead == 'l') ADVANCE(50);
      END_STATE();
    case 58:
      if (lookahead == 'l') ADVANCE(69);
      END_STATE();
    case 59:
      if (lookahead == 'l') ADVANCE(34);
      END_STATE();
    case 60:
      if (lookahead == 'l') ADVANCE(58);
      END_STATE();
    case 61:
      if (lookahead == 'm') ADVANCE(41);
      if (lookahead == 'n') ADVANCE(169);
      END_STATE();
    case 62:
      if (lookahead == 'n') ADVANCE(44);
      END_STATE();
    case 63:
      if (lookahead == 'n') ADVANCE(169);
      END_STATE();
    case 64:
      if (lookahead == 'n') ADVANCE(123);
      END_STATE();
    case 65:
      if (lookahead == 'n') ADVANCE(27);
      END_STATE();
    case 66:
      if (lookahead == 'n') ADVANCE(89);
      END_STATE();
    case 67:
      if (lookahead == 'o') ADVANCE(26);
      END_STATE();
    case 68:
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 69:
      if (lookahead == 'o') ADVANCE(97);
      END_STATE();
    case 70:
      if (lookahead == 'o') ADVANCE(65);
      END_STATE();
    case 71:
      if (lookahead == 'o') ADVANCE(82);
      if (lookahead == 'r') ADVANCE(31);
      END_STATE();
    case 72:
      if (lookahead == 'o') ADVANCE(64);
      END_STATE();
    case 73:
      if (lookahead == 'p') ADVANCE(16);
      END_STATE();
    case 74:
      if (lookahead == 'p') ADVANCE(57);
      END_STATE();
    case 75:
      if (lookahead == 'r') ADVANCE(93);
      END_STATE();
    case 76:
      if (lookahead == 'r') ADVANCE(9);
      END_STATE();
    case 77:
      if (lookahead == 'r') ADVANCE(94);
      END_STATE();
    case 78:
      if (lookahead == 'r') ADVANCE(43);
      END_STATE();
    case 79:
      if (lookahead == 'r') ADVANCE(51);
      END_STATE();
    case 80:
      if (lookahead == 'r') ADVANCE(79);
      END_STATE();
    case 81:
      if (lookahead == 'r') ADVANCE(77);
      END_STATE();
    case 82:
      if (lookahead == 's') ADVANCE(88);
      END_STATE();
    case 83:
      if (lookahead == 's') ADVANCE(73);
      END_STATE();
    case 84:
      if (lookahead == 's') ADVANCE(45);
      END_STATE();
    case 85:
      if (lookahead == 's') ADVANCE(46);
      END_STATE();
    case 86:
      if (lookahead == 's') ADVANCE(33);
      END_STATE();
    case 87:
      if (lookahead == 's') ADVANCE(39);
      END_STATE();
    case 88:
      if (lookahead == 't') ADVANCE(135);
      END_STATE();
    case 89:
      if (lookahead == 't') ADVANCE(10);
      END_STATE();
    case 90:
      if (lookahead == 't') ADVANCE(52);
      END_STATE();
    case 91:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 92:
      if (lookahead == 'u') ADVANCE(74);
      END_STATE();
    case 93:
      if (lookahead == 'u') ADVANCE(32);
      END_STATE();
    case 94:
      if (lookahead == 'u') ADVANCE(59);
      END_STATE();
    case 95:
      if (lookahead == 'v') ADVANCE(38);
      END_STATE();
    case 96:
      if (lookahead == 'v') ADVANCE(42);
      END_STATE();
    case 97:
      if (lookahead == 'w') ADVANCE(11);
      END_STATE();
    case 98:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(101);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(168);
      END_STATE();
    case 99:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      END_STATE();
    case 100:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(167);
      END_STATE();
    case 101:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(168);
      END_STATE();
    case 102:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 103:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 104:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 105:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(104);
      END_STATE();
    case 106:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      END_STATE();
    case 107:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 108:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 109:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(108);
      END_STATE();
    case 110:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 111:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 112:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 113:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(112);
      END_STATE();
    case 114:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(113);
      END_STATE();
    case 115:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      END_STATE();
    case 116:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 117:
      if (eof) ADVANCE(119);
      ADVANCE_MAP(
        '\n', 122,
        '\r', 1,
        '$', 134,
        ';', 165,
        '=', 121,
        '[', 125,
        'a', 155,
        'g', 153,
        'l', 156,
        'p', 159,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(117);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(164);
      END_STATE();
    case 118:
      if (eof) ADVANCE(119);
      ADVANCE_MAP(
        '\n', 122,
        '\r', 1,
        '$', 134,
        ';', 165,
        '[', 125,
        'a', 155,
        'g', 153,
        'h', 144,
        'l', 156,
        'p', 159,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(118);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(164);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_namespace);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(aux_sym__header_section_namespaced_token1);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(anon_sym_condition);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(aux_sym_present_section_token1);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead == 'P') ADVANCE(78);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(anon_sym_ShaderOverride);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(anon_sym_hash);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(anon_sym_hash);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(164);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(anon_sym_allow_duplicate_hash);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(anon_sym_overrule);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(anon_sym_post);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(anon_sym_post);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(164);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(anon_sym_pre);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(anon_sym_pre);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(164);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(anon_sym_local);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(anon_sym_local);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(164);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(anon_sym_global);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(anon_sym_global);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(164);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(aux_sym_commandlist_rarg_token1);
      if (lookahead == '_') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(164);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(aux_sym_commandlist_rarg_token1);
      if (lookahead == 'a') ADVANCE(160);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(164);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(aux_sym_commandlist_rarg_token1);
      if (lookahead == 'a') ADVANCE(151);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(164);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(aux_sym_commandlist_rarg_token1);
      if (lookahead == 'a') ADVANCE(152);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(164);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(aux_sym_commandlist_rarg_token1);
      if (lookahead == 'b') ADVANCE(146);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(164);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(aux_sym_commandlist_rarg_token1);
      if (lookahead == 'c') ADVANCE(145);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(164);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(aux_sym_commandlist_rarg_token1);
      if (lookahead == 'e') ADVANCE(138);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(164);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(aux_sym_commandlist_rarg_token1);
      if (lookahead == 'h') ADVANCE(129);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(164);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(aux_sym_commandlist_rarg_token1);
      if (lookahead == 'l') ADVANCE(140);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(164);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(aux_sym_commandlist_rarg_token1);
      if (lookahead == 'l') ADVANCE(142);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(164);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(aux_sym_commandlist_rarg_token1);
      if (lookahead == 'l') ADVANCE(157);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(164);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(aux_sym_commandlist_rarg_token1);
      if (lookahead == 'l') ADVANCE(158);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(164);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(aux_sym_commandlist_rarg_token1);
      if (lookahead == 'l') ADVANCE(154);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(164);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(aux_sym_commandlist_rarg_token1);
      if (lookahead == 'o') ADVANCE(148);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(164);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(aux_sym_commandlist_rarg_token1);
      if (lookahead == 'o') ADVANCE(147);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(164);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(aux_sym_commandlist_rarg_token1);
      if (lookahead == 'o') ADVANCE(163);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(164);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(aux_sym_commandlist_rarg_token1);
      if (lookahead == 'o') ADVANCE(161);
      if (lookahead == 'r') ADVANCE(149);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(164);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(aux_sym_commandlist_rarg_token1);
      if (lookahead == 's') ADVANCE(150);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(164);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(aux_sym_commandlist_rarg_token1);
      if (lookahead == 's') ADVANCE(162);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(164);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(aux_sym_commandlist_rarg_token1);
      if (lookahead == 't') ADVANCE(136);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(164);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(aux_sym_commandlist_rarg_token1);
      if (lookahead == 'w') ADVANCE(143);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(164);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(aux_sym_commandlist_rarg_token1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(164);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 166:
      ACCEPT_TOKEN(sym_hash_16);
      END_STATE();
    case 167:
      ACCEPT_TOKEN(aux_sym_float_token1);
      if (lookahead == '_') ADVANCE(100);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(98);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(167);
      END_STATE();
    case 168:
      ACCEPT_TOKEN(aux_sym_float_token1);
      if (lookahead == '_') ADVANCE(101);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(168);
      END_STATE();
    case 169:
      ACCEPT_TOKEN(aux_sym_float_token2);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 118},
  [3] = {.lex_state = 117},
  [4] = {.lex_state = 117},
  [5] = {.lex_state = 117},
  [6] = {.lex_state = 117},
  [7] = {.lex_state = 117},
  [8] = {.lex_state = 117},
  [9] = {.lex_state = 117},
  [10] = {.lex_state = 117},
  [11] = {.lex_state = 117},
  [12] = {.lex_state = 117},
  [13] = {.lex_state = 117},
  [14] = {.lex_state = 117},
  [15] = {.lex_state = 117},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 117},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 117},
  [20] = {.lex_state = 117},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 117},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 117},
  [25] = {.lex_state = 117},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 3},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 2},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_namespace] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [aux_sym__header_section_namespaced_token1] = ACTIONS(3),
    [anon_sym_condition] = ACTIONS(1),
    [aux_sym_present_section_token1] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_ShaderOverride] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_hash] = ACTIONS(1),
    [anon_sym_allow_duplicate_hash] = ACTIONS(1),
    [anon_sym_overrule] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_post] = ACTIONS(1),
    [anon_sym_pre] = ACTIONS(1),
    [anon_sym_local] = ACTIONS(1),
    [anon_sym_global] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(5),
    [aux_sym_float_token1] = ACTIONS(1),
    [aux_sym_float_token2] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(69),
    [sym_header_section] = STATE(21),
    [sym__header_section_namespaced] = STATE(46),
    [sym__header_section_conditioned] = STATE(37),
    [sym__section] = STATE(44),
    [sym__named_section] = STATE(39),
    [sym__regular_section] = STATE(39),
    [sym_present_section] = STATE(38),
    [sym_shader_override] = STATE(45),
    [sym_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(23),
    [ts_builtin_sym_end] = ACTIONS(7),
    [anon_sym_namespace] = ACTIONS(9),
    [aux_sym__header_section_namespaced_token1] = ACTIONS(3),
    [anon_sym_condition] = ACTIONS(11),
    [aux_sym_present_section_token1] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_SEMI] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 19,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_hash,
    ACTIONS(23), 1,
      anon_sym_allow_duplicate_hash,
    ACTIONS(25), 1,
      anon_sym_DOLLAR,
    ACTIONS(31), 1,
      aux_sym_commandlist_rarg_token1,
    STATE(2), 1,
      sym_comment,
    STATE(11), 1,
      aux_sym_present_section_repeat1,
    STATE(14), 1,
      sym__expression,
    STATE(26), 1,
      sym_scope_prefix,
    STATE(42), 1,
      sym_timing_prefix,
    STATE(65), 1,
      sym_variable,
    STATE(66), 1,
      sym__key,
    STATE(70), 1,
      sym_commandlist_rarg,
    ACTIONS(17), 2,
      ts_builtin_sym_end,
      aux_sym_present_section_token1,
    ACTIONS(27), 2,
      anon_sym_post,
      anon_sym_pre,
    ACTIONS(29), 2,
      anon_sym_local,
      anon_sym_global,
    STATE(15), 2,
      sym_assignment,
      sym_commandlist,
  [62] = 18,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(25), 1,
      anon_sym_DOLLAR,
    ACTIONS(31), 1,
      aux_sym_commandlist_rarg_token1,
    ACTIONS(35), 1,
      anon_sym_LBRACK,
    ACTIONS(37), 1,
      anon_sym_allow_duplicate_hash,
    STATE(3), 1,
      sym_comment,
    STATE(9), 1,
      aux_sym_present_section_repeat1,
    STATE(14), 1,
      sym__expression,
    STATE(26), 1,
      sym_scope_prefix,
    STATE(42), 1,
      sym_timing_prefix,
    STATE(65), 1,
      sym_variable,
    STATE(66), 1,
      sym__key,
    STATE(70), 1,
      sym_commandlist_rarg,
    ACTIONS(27), 2,
      anon_sym_post,
      anon_sym_pre,
    ACTIONS(29), 2,
      anon_sym_local,
      anon_sym_global,
    ACTIONS(33), 2,
      ts_builtin_sym_end,
      aux_sym_present_section_token1,
    STATE(15), 2,
      sym_assignment,
      sym_commandlist,
  [121] = 17,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(25), 1,
      anon_sym_DOLLAR,
    ACTIONS(31), 1,
      aux_sym_commandlist_rarg_token1,
    ACTIONS(41), 1,
      anon_sym_LBRACK,
    STATE(4), 1,
      sym_comment,
    STATE(5), 1,
      aux_sym_present_section_repeat1,
    STATE(14), 1,
      sym__expression,
    STATE(26), 1,
      sym_scope_prefix,
    STATE(42), 1,
      sym_timing_prefix,
    STATE(65), 1,
      sym_variable,
    STATE(66), 1,
      sym__key,
    STATE(70), 1,
      sym_commandlist_rarg,
    ACTIONS(27), 2,
      anon_sym_post,
      anon_sym_pre,
    ACTIONS(29), 2,
      anon_sym_local,
      anon_sym_global,
    ACTIONS(39), 2,
      ts_builtin_sym_end,
      aux_sym_present_section_token1,
    STATE(15), 2,
      sym_assignment,
      sym_commandlist,
  [177] = 17,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(25), 1,
      anon_sym_DOLLAR,
    ACTIONS(31), 1,
      aux_sym_commandlist_rarg_token1,
    ACTIONS(45), 1,
      anon_sym_LBRACK,
    STATE(5), 1,
      sym_comment,
    STATE(6), 1,
      aux_sym_present_section_repeat1,
    STATE(14), 1,
      sym__expression,
    STATE(26), 1,
      sym_scope_prefix,
    STATE(42), 1,
      sym_timing_prefix,
    STATE(65), 1,
      sym_variable,
    STATE(66), 1,
      sym__key,
    STATE(70), 1,
      sym_commandlist_rarg,
    ACTIONS(27), 2,
      anon_sym_post,
      anon_sym_pre,
    ACTIONS(29), 2,
      anon_sym_local,
      anon_sym_global,
    ACTIONS(43), 2,
      ts_builtin_sym_end,
      aux_sym_present_section_token1,
    STATE(15), 2,
      sym_assignment,
      sym_commandlist,
  [233] = 16,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(49), 1,
      anon_sym_LBRACK,
    ACTIONS(51), 1,
      anon_sym_DOLLAR,
    ACTIONS(60), 1,
      aux_sym_commandlist_rarg_token1,
    STATE(14), 1,
      sym__expression,
    STATE(26), 1,
      sym_scope_prefix,
    STATE(42), 1,
      sym_timing_prefix,
    STATE(65), 1,
      sym_variable,
    STATE(66), 1,
      sym__key,
    STATE(70), 1,
      sym_commandlist_rarg,
    ACTIONS(47), 2,
      ts_builtin_sym_end,
      aux_sym_present_section_token1,
    ACTIONS(54), 2,
      anon_sym_post,
      anon_sym_pre,
    ACTIONS(57), 2,
      anon_sym_local,
      anon_sym_global,
    STATE(6), 2,
      sym_comment,
      aux_sym_present_section_repeat1,
    STATE(15), 2,
      sym_assignment,
      sym_commandlist,
  [287] = 17,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(25), 1,
      anon_sym_DOLLAR,
    ACTIONS(31), 1,
      aux_sym_commandlist_rarg_token1,
    ACTIONS(65), 1,
      anon_sym_LBRACK,
    STATE(7), 1,
      sym_comment,
    STATE(12), 1,
      aux_sym_present_section_repeat1,
    STATE(14), 1,
      sym__expression,
    STATE(26), 1,
      sym_scope_prefix,
    STATE(42), 1,
      sym_timing_prefix,
    STATE(65), 1,
      sym_variable,
    STATE(66), 1,
      sym__key,
    STATE(70), 1,
      sym_commandlist_rarg,
    ACTIONS(27), 2,
      anon_sym_post,
      anon_sym_pre,
    ACTIONS(29), 2,
      anon_sym_local,
      anon_sym_global,
    ACTIONS(63), 2,
      ts_builtin_sym_end,
      aux_sym_present_section_token1,
    STATE(15), 2,
      sym_assignment,
      sym_commandlist,
  [343] = 17,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(25), 1,
      anon_sym_DOLLAR,
    ACTIONS(31), 1,
      aux_sym_commandlist_rarg_token1,
    ACTIONS(69), 1,
      anon_sym_LBRACK,
    STATE(6), 1,
      aux_sym_present_section_repeat1,
    STATE(8), 1,
      sym_comment,
    STATE(14), 1,
      sym__expression,
    STATE(26), 1,
      sym_scope_prefix,
    STATE(42), 1,
      sym_timing_prefix,
    STATE(65), 1,
      sym_variable,
    STATE(66), 1,
      sym__key,
    STATE(70), 1,
      sym_commandlist_rarg,
    ACTIONS(27), 2,
      anon_sym_post,
      anon_sym_pre,
    ACTIONS(29), 2,
      anon_sym_local,
      anon_sym_global,
    ACTIONS(67), 2,
      ts_builtin_sym_end,
      aux_sym_present_section_token1,
    STATE(15), 2,
      sym_assignment,
      sym_commandlist,
  [399] = 17,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(25), 1,
      anon_sym_DOLLAR,
    ACTIONS(31), 1,
      aux_sym_commandlist_rarg_token1,
    ACTIONS(73), 1,
      anon_sym_LBRACK,
    STATE(6), 1,
      aux_sym_present_section_repeat1,
    STATE(9), 1,
      sym_comment,
    STATE(14), 1,
      sym__expression,
    STATE(26), 1,
      sym_scope_prefix,
    STATE(42), 1,
      sym_timing_prefix,
    STATE(65), 1,
      sym_variable,
    STATE(66), 1,
      sym__key,
    STATE(70), 1,
      sym_commandlist_rarg,
    ACTIONS(27), 2,
      anon_sym_post,
      anon_sym_pre,
    ACTIONS(29), 2,
      anon_sym_local,
      anon_sym_global,
    ACTIONS(71), 2,
      ts_builtin_sym_end,
      aux_sym_present_section_token1,
    STATE(15), 2,
      sym_assignment,
      sym_commandlist,
  [455] = 17,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(25), 1,
      anon_sym_DOLLAR,
    ACTIONS(31), 1,
      aux_sym_commandlist_rarg_token1,
    ACTIONS(77), 1,
      anon_sym_LBRACK,
    STATE(8), 1,
      aux_sym_present_section_repeat1,
    STATE(10), 1,
      sym_comment,
    STATE(14), 1,
      sym__expression,
    STATE(26), 1,
      sym_scope_prefix,
    STATE(42), 1,
      sym_timing_prefix,
    STATE(65), 1,
      sym_variable,
    STATE(66), 1,
      sym__key,
    STATE(70), 1,
      sym_commandlist_rarg,
    ACTIONS(27), 2,
      anon_sym_post,
      anon_sym_pre,
    ACTIONS(29), 2,
      anon_sym_local,
      anon_sym_global,
    ACTIONS(75), 2,
      ts_builtin_sym_end,
      aux_sym_present_section_token1,
    STATE(15), 2,
      sym_assignment,
      sym_commandlist,
  [511] = 17,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(25), 1,
      anon_sym_DOLLAR,
    ACTIONS(31), 1,
      aux_sym_commandlist_rarg_token1,
    ACTIONS(81), 1,
      anon_sym_LBRACK,
    STATE(6), 1,
      aux_sym_present_section_repeat1,
    STATE(11), 1,
      sym_comment,
    STATE(14), 1,
      sym__expression,
    STATE(26), 1,
      sym_scope_prefix,
    STATE(42), 1,
      sym_timing_prefix,
    STATE(65), 1,
      sym_variable,
    STATE(66), 1,
      sym__key,
    STATE(70), 1,
      sym_commandlist_rarg,
    ACTIONS(27), 2,
      anon_sym_post,
      anon_sym_pre,
    ACTIONS(29), 2,
      anon_sym_local,
      anon_sym_global,
    ACTIONS(79), 2,
      ts_builtin_sym_end,
      aux_sym_present_section_token1,
    STATE(15), 2,
      sym_assignment,
      sym_commandlist,
  [567] = 17,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(25), 1,
      anon_sym_DOLLAR,
    ACTIONS(31), 1,
      aux_sym_commandlist_rarg_token1,
    ACTIONS(85), 1,
      anon_sym_LBRACK,
    STATE(6), 1,
      aux_sym_present_section_repeat1,
    STATE(12), 1,
      sym_comment,
    STATE(14), 1,
      sym__expression,
    STATE(26), 1,
      sym_scope_prefix,
    STATE(42), 1,
      sym_timing_prefix,
    STATE(65), 1,
      sym_variable,
    STATE(66), 1,
      sym__key,
    STATE(70), 1,
      sym_commandlist_rarg,
    ACTIONS(27), 2,
      anon_sym_post,
      anon_sym_pre,
    ACTIONS(29), 2,
      anon_sym_local,
      anon_sym_global,
    ACTIONS(83), 2,
      ts_builtin_sym_end,
      aux_sym_present_section_token1,
    STATE(15), 2,
      sym_assignment,
      sym_commandlist,
  [623] = 5,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(13), 1,
      sym_comment,
    ACTIONS(87), 4,
      ts_builtin_sym_end,
      anon_sym_EQ,
      aux_sym_present_section_token1,
      anon_sym_DOLLAR,
    ACTIONS(89), 6,
      anon_sym_LBRACK,
      anon_sym_post,
      anon_sym_pre,
      anon_sym_local,
      anon_sym_global,
      aux_sym_commandlist_rarg_token1,
  [647] = 5,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(14), 1,
      sym_comment,
    ACTIONS(91), 3,
      ts_builtin_sym_end,
      aux_sym_present_section_token1,
      anon_sym_DOLLAR,
    ACTIONS(93), 6,
      anon_sym_LBRACK,
      anon_sym_post,
      anon_sym_pre,
      anon_sym_local,
      anon_sym_global,
      aux_sym_commandlist_rarg_token1,
  [670] = 5,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(15), 1,
      sym_comment,
    ACTIONS(95), 3,
      ts_builtin_sym_end,
      aux_sym_present_section_token1,
      anon_sym_DOLLAR,
    ACTIONS(97), 6,
      anon_sym_LBRACK,
      anon_sym_post,
      anon_sym_pre,
      anon_sym_local,
      anon_sym_global,
      aux_sym_commandlist_rarg_token1,
  [693] = 11,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      aux_sym_present_section_token1,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(99), 1,
      ts_builtin_sym_end,
    STATE(16), 1,
      sym_comment,
    STATE(18), 1,
      aux_sym_source_file_repeat1,
    STATE(38), 1,
      sym_present_section,
    STATE(44), 1,
      sym__section,
    STATE(45), 1,
      sym_shader_override,
    STATE(39), 2,
      sym__named_section,
      sym__regular_section,
  [728] = 5,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(17), 1,
      sym_comment,
    ACTIONS(101), 3,
      ts_builtin_sym_end,
      aux_sym_present_section_token1,
      anon_sym_DOLLAR,
    ACTIONS(103), 6,
      anon_sym_LBRACK,
      anon_sym_post,
      anon_sym_pre,
      anon_sym_local,
      anon_sym_global,
      aux_sym_commandlist_rarg_token1,
  [751] = 10,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(105), 1,
      ts_builtin_sym_end,
    ACTIONS(107), 1,
      aux_sym_present_section_token1,
    ACTIONS(110), 1,
      anon_sym_LBRACK,
    STATE(38), 1,
      sym_present_section,
    STATE(44), 1,
      sym__section,
    STATE(45), 1,
      sym_shader_override,
    STATE(18), 2,
      sym_comment,
      aux_sym_source_file_repeat1,
    STATE(39), 2,
      sym__named_section,
      sym__regular_section,
  [784] = 5,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(19), 1,
      sym_comment,
    ACTIONS(113), 3,
      ts_builtin_sym_end,
      aux_sym_present_section_token1,
      anon_sym_DOLLAR,
    ACTIONS(115), 6,
      anon_sym_LBRACK,
      anon_sym_post,
      anon_sym_pre,
      anon_sym_local,
      anon_sym_global,
      aux_sym_commandlist_rarg_token1,
  [807] = 5,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(20), 1,
      sym_comment,
    ACTIONS(117), 3,
      ts_builtin_sym_end,
      aux_sym_present_section_token1,
      anon_sym_DOLLAR,
    ACTIONS(119), 6,
      anon_sym_LBRACK,
      anon_sym_post,
      anon_sym_pre,
      anon_sym_local,
      anon_sym_global,
      aux_sym_commandlist_rarg_token1,
  [830] = 11,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      aux_sym_present_section_token1,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(121), 1,
      ts_builtin_sym_end,
    STATE(16), 1,
      aux_sym_source_file_repeat1,
    STATE(21), 1,
      sym_comment,
    STATE(38), 1,
      sym_present_section,
    STATE(44), 1,
      sym__section,
    STATE(45), 1,
      sym_shader_override,
    STATE(39), 2,
      sym__named_section,
      sym__regular_section,
  [865] = 5,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(22), 1,
      sym_comment,
    ACTIONS(123), 3,
      ts_builtin_sym_end,
      aux_sym_present_section_token1,
      anon_sym_DOLLAR,
    ACTIONS(125), 6,
      anon_sym_LBRACK,
      anon_sym_post,
      anon_sym_pre,
      anon_sym_local,
      anon_sym_global,
      aux_sym_commandlist_rarg_token1,
  [888] = 11,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      aux_sym_present_section_token1,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(121), 1,
      ts_builtin_sym_end,
    STATE(18), 1,
      aux_sym_source_file_repeat1,
    STATE(23), 1,
      sym_comment,
    STATE(38), 1,
      sym_present_section,
    STATE(44), 1,
      sym__section,
    STATE(45), 1,
      sym_shader_override,
    STATE(39), 2,
      sym__named_section,
      sym__regular_section,
  [923] = 5,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(24), 1,
      sym_comment,
    ACTIONS(127), 3,
      ts_builtin_sym_end,
      aux_sym_present_section_token1,
      anon_sym_DOLLAR,
    ACTIONS(129), 6,
      anon_sym_LBRACK,
      anon_sym_post,
      anon_sym_pre,
      anon_sym_local,
      anon_sym_global,
      aux_sym_commandlist_rarg_token1,
  [946] = 5,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(25), 1,
      sym_comment,
    ACTIONS(131), 3,
      ts_builtin_sym_end,
      aux_sym_present_section_token1,
      anon_sym_DOLLAR,
    ACTIONS(133), 6,
      anon_sym_LBRACK,
      anon_sym_post,
      anon_sym_pre,
      anon_sym_local,
      anon_sym_global,
      aux_sym_commandlist_rarg_token1,
  [969] = 8,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(25), 1,
      anon_sym_DOLLAR,
    STATE(26), 1,
      sym_comment,
    STATE(41), 1,
      sym_timing_prefix,
    STATE(63), 1,
      sym__key,
    STATE(65), 1,
      sym_variable,
    ACTIONS(135), 2,
      anon_sym_post,
      anon_sym_pre,
  [995] = 7,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(27), 1,
      sym_comment,
    STATE(80), 1,
      sym__value,
    STATE(83), 1,
      sym_eval_value,
    STATE(87), 1,
      sym_float,
    ACTIONS(137), 2,
      aux_sym_float_token1,
      aux_sym_float_token2,
  [1018] = 7,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(28), 1,
      sym_comment,
    STATE(80), 1,
      sym__value,
    STATE(85), 1,
      sym_eval_value,
    STATE(87), 1,
      sym_float,
    ACTIONS(137), 2,
      aux_sym_float_token1,
      aux_sym_float_token2,
  [1041] = 6,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(141), 1,
      anon_sym_condition,
    ACTIONS(143), 1,
      anon_sym_LBRACK,
    STATE(29), 1,
      sym_comment,
    ACTIONS(139), 2,
      ts_builtin_sym_end,
      aux_sym_present_section_token1,
  [1061] = 6,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(147), 1,
      anon_sym_namespace,
    ACTIONS(149), 1,
      anon_sym_LBRACK,
    STATE(30), 1,
      sym_comment,
    ACTIONS(145), 2,
      ts_builtin_sym_end,
      aux_sym_present_section_token1,
  [1081] = 6,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(17), 1,
      sym__value,
    STATE(25), 1,
      sym_float,
    STATE(31), 1,
      sym_comment,
    ACTIONS(151), 2,
      aux_sym_float_token1,
      aux_sym_float_token2,
  [1101] = 6,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(20), 1,
      sym__value,
    STATE(25), 1,
      sym_float,
    STATE(32), 1,
      sym_comment,
    ACTIONS(151), 2,
      aux_sym_float_token1,
      aux_sym_float_token2,
  [1121] = 5,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(33), 1,
      sym_comment,
    STATE(77), 1,
      sym_allow_duplicate_hash_value,
    ACTIONS(153), 3,
      anon_sym_overrule,
      anon_sym_true,
      anon_sym_false,
  [1139] = 5,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(34), 1,
      sym_comment,
    STATE(84), 1,
      sym_allow_duplicate_hash_value,
    ACTIONS(153), 3,
      anon_sym_overrule,
      anon_sym_true,
      anon_sym_false,
  [1157] = 6,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(22), 1,
      sym__value,
    STATE(25), 1,
      sym_float,
    STATE(35), 1,
      sym_comment,
    ACTIONS(151), 2,
      aux_sym_float_token1,
      aux_sym_float_token2,
  [1177] = 5,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    STATE(36), 1,
      sym_comment,
    ACTIONS(155), 2,
      ts_builtin_sym_end,
      aux_sym_present_section_token1,
  [1194] = 5,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(161), 1,
      anon_sym_LBRACK,
    STATE(37), 1,
      sym_comment,
    ACTIONS(159), 2,
      ts_builtin_sym_end,
      aux_sym_present_section_token1,
  [1211] = 5,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(165), 1,
      anon_sym_LBRACK,
    STATE(38), 1,
      sym_comment,
    ACTIONS(163), 2,
      ts_builtin_sym_end,
      aux_sym_present_section_token1,
  [1228] = 5,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(169), 1,
      anon_sym_LBRACK,
    STATE(39), 1,
      sym_comment,
    ACTIONS(167), 2,
      ts_builtin_sym_end,
      aux_sym_present_section_token1,
  [1245] = 4,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(40), 1,
      sym_comment,
    ACTIONS(171), 3,
      anon_sym_DOLLAR,
      anon_sym_post,
      anon_sym_pre,
  [1260] = 6,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(25), 1,
      anon_sym_DOLLAR,
    STATE(41), 1,
      sym_comment,
    STATE(54), 1,
      sym__key,
    STATE(65), 1,
      sym_variable,
  [1279] = 6,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(25), 1,
      anon_sym_DOLLAR,
    STATE(42), 1,
      sym_comment,
    STATE(63), 1,
      sym__key,
    STATE(65), 1,
      sym_variable,
  [1298] = 5,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(175), 1,
      anon_sym_LBRACK,
    STATE(43), 1,
      sym_comment,
    ACTIONS(173), 2,
      ts_builtin_sym_end,
      aux_sym_present_section_token1,
  [1315] = 5,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(179), 1,
      anon_sym_LBRACK,
    STATE(44), 1,
      sym_comment,
    ACTIONS(177), 2,
      ts_builtin_sym_end,
      aux_sym_present_section_token1,
  [1332] = 5,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(183), 1,
      anon_sym_LBRACK,
    STATE(45), 1,
      sym_comment,
    ACTIONS(181), 2,
      ts_builtin_sym_end,
      aux_sym_present_section_token1,
  [1349] = 5,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(161), 1,
      anon_sym_LBRACK,
    STATE(46), 1,
      sym_comment,
    ACTIONS(159), 2,
      ts_builtin_sym_end,
      aux_sym_present_section_token1,
  [1366] = 4,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(47), 1,
      sym_comment,
    ACTIONS(185), 2,
      anon_sym_EQ,
      anon_sym_RBRACK,
  [1380] = 5,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(187), 1,
      aux_sym_commandlist_rarg_token1,
    STATE(48), 1,
      sym_comment,
    STATE(86), 1,
      sym_string,
  [1396] = 5,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(189), 1,
      aux_sym_commandlist_rarg_token1,
    STATE(49), 1,
      sym_comment,
    STATE(62), 1,
      sym_identifier,
  [1412] = 5,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(191), 1,
      aux_sym_commandlist_rarg_token1,
    STATE(19), 1,
      sym_commandlist_rarg,
    STATE(50), 1,
      sym_comment,
  [1428] = 5,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(189), 1,
      aux_sym_commandlist_rarg_token1,
    STATE(51), 1,
      sym_comment,
    STATE(68), 1,
      sym_identifier,
  [1444] = 5,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(187), 1,
      aux_sym_commandlist_rarg_token1,
    STATE(52), 1,
      sym_comment,
    STATE(74), 1,
      sym_string,
  [1460] = 4,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(193), 1,
      anon_sym_ShaderOverride,
    STATE(53), 1,
      sym_comment,
  [1473] = 4,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(195), 1,
      anon_sym_EQ,
    STATE(54), 1,
      sym_comment,
  [1486] = 4,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(197), 1,
      anon_sym_EQ,
    STATE(55), 1,
      sym_comment,
  [1499] = 4,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(199), 1,
      anon_sym_EQ,
    STATE(56), 1,
      sym_comment,
  [1512] = 4,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(201), 1,
      anon_sym_EQ,
    STATE(57), 1,
      sym_comment,
  [1525] = 4,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(203), 1,
      anon_sym_EQ,
    STATE(58), 1,
      sym_comment,
  [1538] = 4,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(205), 1,
      anon_sym_EQ,
    STATE(59), 1,
      sym_comment,
  [1551] = 4,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(207), 1,
      sym_hash_16,
    STATE(60), 1,
      sym_comment,
  [1564] = 4,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(209), 1,
      aux_sym_commandlist_rarg_token1,
    STATE(61), 1,
      sym_comment,
  [1577] = 4,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(211), 1,
      anon_sym_EQ,
    STATE(62), 1,
      sym_comment,
  [1590] = 4,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(213), 1,
      anon_sym_EQ,
    STATE(63), 1,
      sym_comment,
  [1603] = 4,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(215), 1,
      anon_sym_EQ,
    STATE(64), 1,
      sym_comment,
  [1616] = 4,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(217), 1,
      anon_sym_EQ,
    STATE(65), 1,
      sym_comment,
  [1629] = 4,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(219), 1,
      anon_sym_EQ,
    STATE(66), 1,
      sym_comment,
  [1642] = 4,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(221), 1,
      aux_sym_commandlist_rarg_token1,
    STATE(67), 1,
      sym_comment,
  [1655] = 4,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(223), 1,
      anon_sym_RBRACK,
    STATE(68), 1,
      sym_comment,
  [1668] = 4,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(225), 1,
      ts_builtin_sym_end,
    STATE(69), 1,
      sym_comment,
  [1681] = 4,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(227), 1,
      anon_sym_EQ,
    STATE(70), 1,
      sym_comment,
  [1694] = 4,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(229), 1,
      anon_sym_EQ,
    STATE(71), 1,
      sym_comment,
  [1707] = 4,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(231), 1,
      anon_sym_DOLLAR,
    STATE(72), 1,
      sym_comment,
  [1720] = 3,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(233), 1,
      aux_sym__header_section_namespaced_token1,
    STATE(73), 1,
      sym_comment,
  [1730] = 3,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(235), 1,
      aux_sym__header_section_namespaced_token1,
    STATE(74), 1,
      sym_comment,
  [1740] = 3,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(237), 1,
      aux_sym__header_section_namespaced_token1,
    STATE(75), 1,
      sym_comment,
  [1750] = 3,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(239), 1,
      aux_sym__header_section_namespaced_token1,
    STATE(76), 1,
      sym_comment,
  [1760] = 3,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(241), 1,
      aux_sym__header_section_namespaced_token1,
    STATE(77), 1,
      sym_comment,
  [1770] = 3,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(209), 1,
      aux_sym__header_section_namespaced_token1,
    STATE(78), 1,
      sym_comment,
  [1780] = 3,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(127), 1,
      aux_sym__header_section_namespaced_token1,
    STATE(79), 1,
      sym_comment,
  [1790] = 3,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(243), 1,
      aux_sym__header_section_namespaced_token1,
    STATE(80), 1,
      sym_comment,
  [1800] = 3,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(245), 1,
      aux_sym__header_section_namespaced_token1,
    STATE(81), 1,
      sym_comment,
  [1810] = 3,
    ACTIONS(3), 1,
      aux_sym__header_section_namespaced_token1,
    ACTIONS(247), 1,
      anon_sym_SEMI,
    STATE(82), 1,
      sym_comment,
  [1820] = 3,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(249), 1,
      aux_sym__header_section_namespaced_token1,
    STATE(83), 1,
      sym_comment,
  [1830] = 3,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(251), 1,
      aux_sym__header_section_namespaced_token1,
    STATE(84), 1,
      sym_comment,
  [1840] = 3,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(253), 1,
      aux_sym__header_section_namespaced_token1,
    STATE(85), 1,
      sym_comment,
  [1850] = 3,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(255), 1,
      aux_sym__header_section_namespaced_token1,
    STATE(86), 1,
      sym_comment,
  [1860] = 3,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(131), 1,
      aux_sym__header_section_namespaced_token1,
    STATE(87), 1,
      sym_comment,
  [1870] = 1,
    ACTIONS(257), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 62,
  [SMALL_STATE(4)] = 121,
  [SMALL_STATE(5)] = 177,
  [SMALL_STATE(6)] = 233,
  [SMALL_STATE(7)] = 287,
  [SMALL_STATE(8)] = 343,
  [SMALL_STATE(9)] = 399,
  [SMALL_STATE(10)] = 455,
  [SMALL_STATE(11)] = 511,
  [SMALL_STATE(12)] = 567,
  [SMALL_STATE(13)] = 623,
  [SMALL_STATE(14)] = 647,
  [SMALL_STATE(15)] = 670,
  [SMALL_STATE(16)] = 693,
  [SMALL_STATE(17)] = 728,
  [SMALL_STATE(18)] = 751,
  [SMALL_STATE(19)] = 784,
  [SMALL_STATE(20)] = 807,
  [SMALL_STATE(21)] = 830,
  [SMALL_STATE(22)] = 865,
  [SMALL_STATE(23)] = 888,
  [SMALL_STATE(24)] = 923,
  [SMALL_STATE(25)] = 946,
  [SMALL_STATE(26)] = 969,
  [SMALL_STATE(27)] = 995,
  [SMALL_STATE(28)] = 1018,
  [SMALL_STATE(29)] = 1041,
  [SMALL_STATE(30)] = 1061,
  [SMALL_STATE(31)] = 1081,
  [SMALL_STATE(32)] = 1101,
  [SMALL_STATE(33)] = 1121,
  [SMALL_STATE(34)] = 1139,
  [SMALL_STATE(35)] = 1157,
  [SMALL_STATE(36)] = 1177,
  [SMALL_STATE(37)] = 1194,
  [SMALL_STATE(38)] = 1211,
  [SMALL_STATE(39)] = 1228,
  [SMALL_STATE(40)] = 1245,
  [SMALL_STATE(41)] = 1260,
  [SMALL_STATE(42)] = 1279,
  [SMALL_STATE(43)] = 1298,
  [SMALL_STATE(44)] = 1315,
  [SMALL_STATE(45)] = 1332,
  [SMALL_STATE(46)] = 1349,
  [SMALL_STATE(47)] = 1366,
  [SMALL_STATE(48)] = 1380,
  [SMALL_STATE(49)] = 1396,
  [SMALL_STATE(50)] = 1412,
  [SMALL_STATE(51)] = 1428,
  [SMALL_STATE(52)] = 1444,
  [SMALL_STATE(53)] = 1460,
  [SMALL_STATE(54)] = 1473,
  [SMALL_STATE(55)] = 1486,
  [SMALL_STATE(56)] = 1499,
  [SMALL_STATE(57)] = 1512,
  [SMALL_STATE(58)] = 1525,
  [SMALL_STATE(59)] = 1538,
  [SMALL_STATE(60)] = 1551,
  [SMALL_STATE(61)] = 1564,
  [SMALL_STATE(62)] = 1577,
  [SMALL_STATE(63)] = 1590,
  [SMALL_STATE(64)] = 1603,
  [SMALL_STATE(65)] = 1616,
  [SMALL_STATE(66)] = 1629,
  [SMALL_STATE(67)] = 1642,
  [SMALL_STATE(68)] = 1655,
  [SMALL_STATE(69)] = 1668,
  [SMALL_STATE(70)] = 1681,
  [SMALL_STATE(71)] = 1694,
  [SMALL_STATE(72)] = 1707,
  [SMALL_STATE(73)] = 1720,
  [SMALL_STATE(74)] = 1730,
  [SMALL_STATE(75)] = 1740,
  [SMALL_STATE(76)] = 1750,
  [SMALL_STATE(77)] = 1760,
  [SMALL_STATE(78)] = 1770,
  [SMALL_STATE(79)] = 1780,
  [SMALL_STATE(80)] = 1790,
  [SMALL_STATE(81)] = 1800,
  [SMALL_STATE(82)] = 1810,
  [SMALL_STATE(83)] = 1820,
  [SMALL_STATE(84)] = 1830,
  [SMALL_STATE(85)] = 1840,
  [SMALL_STATE(86)] = 1850,
  [SMALL_STATE(87)] = 1860,
  [SMALL_STATE(88)] = 1870,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_shader_override, 5, 0, 5),
  [19] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_shader_override, 5, 0, 5),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_shader_override, 9, 0, 9),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_shader_override, 9, 0, 9),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_present_section, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_present_section, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_present_section, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_present_section, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_present_section_repeat1, 2, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_present_section_repeat1, 2, 0, 0),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_present_section_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_present_section_repeat1, 2, 0, 0), SHIFT_REPEAT(72),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_present_section_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_present_section_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_shader_override, 13, 0, 13),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_shader_override, 13, 0, 13),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_shader_override, 10, 0, 12),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_shader_override, 10, 0, 12),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_shader_override, 10, 0, 11),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_shader_override, 10, 0, 11),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_shader_override, 9, 0, 10),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_shader_override, 9, 0, 10),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_shader_override, 6, 0, 6),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_shader_override, 6, 0, 6),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_shader_override, 14, 0, 14),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_shader_override, 14, 0, 14),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_commandlist_rarg, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_commandlist_rarg, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_present_section_repeat1, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_present_section_repeat1, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [110] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_commandlist, 3, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_commandlist, 3, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 4, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 4, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 5, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 5, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float, 1, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 1, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__value, 1, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__header_section_namespaced, 4, 0, 3),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__header_section_namespaced, 4, 0, 3),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__header_section_conditioned, 4, 0, 4),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__header_section_conditioned, 4, 0, 4),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__header_section_namespaced, 8, 0, 7),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__header_section_namespaced, 8, 0, 7),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_section, 1, 0, 1),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header_section, 1, 0, 1),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__regular_section, 1, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__regular_section, 1, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__section, 1, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__section, 1, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scope_prefix, 1, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__header_section_conditioned, 8, 0, 8),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__header_section_conditioned, 8, 0, 8),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__named_section, 1, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__named_section, 1, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 2, 0, 2),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__key, 1, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [225] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_timing_prefix, 1, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_allow_duplicate_hash_value, 1, 0, 0),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_eval_value, 1, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_iiidm(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "iiidm",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
